psql -v --username "$POSTGRES_USER" --password "$POSTGRES_PASSWORD"
    --dbname "$POSTGRES_DB"
<<-EOSQL
    CREATE USER '$POSTGRES_USER';
    CREATE DATABASE $POSTGRES_DB;
    GRANT ALL PRIVILIGES ON DATABASE '$POSTGRES_DB' TO '$POSTGRES_USER';
EOSQL