import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
	const [likes, setLikes] = useState(0)
	const names = ['Ada Lovelace', 'Grace Hopper', 'Margaret Hamilton']
	function handleClick() {
		setLikes(likes + 1)
	}

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
	  <main>
		<Header title="I love react" />
		<ul>
        {names.map((name) => (
          <li key={name}>{name}</li>
        ))}
      </ul>
	  <button onClick={handleClick} >Like({likes})</button>
	  </main>
    </>
  )
}
