version: "3.9"
services:
  nextjs:
    build:
      context: ./frontend
    env_file:
      - ./frontend/website/.env
    ports:
      - '3000:3000'
  db:
    build:
      context: ./database/
    container_name: "database"
    restart: unless-stopped
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "data"
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local
