version: "3.9"
services:
  db:
    image: postgres:15.1-alpine
    restart: unless-stopped
    env_file:
      - ./database/.env
    ports:
      - '5432:5432'
    volumes:
      - appdb:/var/lib/postgresql/data
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3000"
volumes:
  app_db:
    name: appdb